version: '3.8'

services:
  cassandra:
    image: cassandra:5.0
    container_name: genomic-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=GenomicCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - MAX_HEAP_SIZE=4G
      - HEAP_NEWSIZE=800M
    volumes:
      - ./data/cassandra_data:/var/lib/cassandra
      - ./config/cassandra_schema.cql:/docker-entrypoint-initdb.d/init.cql
    networks:
      - genomics_network

  spark-master:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - JAVA_HOME=/opt/bitnami/java
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./src:/opt/bitnami/spark/app
      - ./data:/opt/bitnami/spark/data
    networks:
      - genomics_network

  spark-worker:
    image: bitnamilegacy/spark:3.5.1
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_MASTER_HOST=spark-master
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - PYSPARK_PYTHON=/usr/bin/python3
    volumes:
      - ./src:/opt/bitnami/spark/app
      - ./data:/opt/bitnami/spark/data
    extra_hosts:
      - "spark-master:host-gateway"

networks:
  genomics_network:
    driver: bridge
